{% set name = "hyram" %}
{% set version = "5.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hyram-{{ version }}.tar.gz
  sha256: 2865f9acb3d6a5eaa549f48f2b50db16e680c5a714bcad51bf4117da10a1e215

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }},<3.11
    - matplotlib-base
    - scipy
    - coolprop >=6.3
    - numpy

test:
  imports:
    - hyram
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://hyram.sandia.gov/
  summary: Hydrogen Plus Other Alternative Fuels Risk Assessment Models Python Package
  license: GPL-3.0-only
  license_file:
    - COPYING.txt

extra:
  recipe-maintainers:
    - EthanHecht
    - bdehrha
    - bliu1013
